version: '2.1'

services:
  legal-integration-tests:
      command: test -- --steps --grep 'I can fill in Organisation details for Claimant, Defendant, Claim amount and Submit the claim'
      environment:
        - http_proxy=http://zap-proxy:8080
        - https_proxy=http://zap-proxy:8080
        - no_proxy=idam-api,remote-webdriver,claim-store-api
      depends_on:
        zap-proxy:
          condition: service_healthy
