version: '2.1'

services:
  integration-tests:
    command: test -- --steps --grep 'I can as an Individual make a claim against an Individual Without a defendant email address and are able to pay on the Gov Pay page'
    environment:
      - http_proxy=http://zap-proxy:8080
      - https_proxy=http://zap-proxy:8080
      - no_proxy=idam-api,remote-webdriver,claim-store-api
    depends_on:
      zap-proxy:
        condition: service_healthy
